######################################################################
# Automatically generated by qmake (3.0) s�b. dic. 23 19:43:10 2017
######################################################################

TEMPLATE = app
TARGET = main
INCLUDEPATH += .

# Input
HEADERS += include/3DObject.h \
           include/button.h \
           include/CImg.h \
           include/file_ply_stl.h \
           include/fps.h \
           include/light.h \
           include/manageView.h \
           include/material.h \
           include/models.h \
           include/objects.h \
           include/plank.h \
           include/texture.h \
           include/types.h \
           include/vertex.h \
           include/wattRegulator.h
SOURCES += src/3DObject.cc \
           src/button.cc \
           src/file_ply_stl.cc \
           src/fps.cc \
           src/light.cc \
           src/manageView.cc \
           src/material.cc \
           src/models.cc \
           src/objects.cc \
           src/plank.cc \
           src/scene.cc \
           src/texture.cc \
           src/wattRegulator.cc
